/* xr_grid_entity_packet.h -- the 100-byte fabric entity packet, in C.
 *
 * GENERATED by `lake exe packet_emit` in v-sekai-multiplayer-fabric/lean-entity-packet.
 * Do not edit: edit EntityPacket/Codec.lean, which is where the layout is specified and where
 * the Plausible roundtrip properties hold it, then emit again.
 *
 * The wire is fully integral -- no floats anywhere -- so position is int64 absolute
 * micrometres and velocity is an int16 scaled against V_MAX. That is what lets the same
 * hundred bytes be compared byte for byte across Lean, C, C++ and GDScript, which
 * packet_golden.csv is for.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef XR_GRID_ENTITY_PACKET_H
#define XR_GRID_ENTITY_PACKET_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define XR_PACKET_SIZE 100
#define XR_PACKET_PAYLOAD_OFFSET 58
#define XR_PACKET_PAYLOAD_LEN 42

/* The i16 velocity scale, in micrometres per tick. A velocity field means nothing without the
 * scale it was divided by, so it travels with the layout rather than beside it. Same number as
 * PBVH_V_MAX_PHYSICAL_DEFAULT in lean-spatial-oracle's predictive_bvh.h. */
#define XR_PACKET_V_MAX_PHYSICAL_DEFAULT_UM_PER_TICK 500000

/* Where each field sits on the wire. Emitted from Codec.lean's own offsets. */
#define XR_PACKET_OFF_GID 0
#define XR_PACKET_OFF_POS 4
#define XR_PACKET_OFF_VEL 28
#define XR_PACKET_OFF_HLC 40
#define XR_PACKET_OFF_CLASS_OWNER 44
#define XR_PACKET_OFF_SUB_INDEX 48
#define XR_PACKET_OFF_ROT 52

typedef struct {
	uint32_t gid;
	int64_t pos_um_x, pos_um_y, pos_um_z;
	int16_t vel_x, vel_y, vel_z;
	uint32_t hlc;
	uint32_t class_owner; /* (class << 24) | owner */
	uint32_t sub_index;
	int16_t rot_x, rot_y, rot_z; /* swing-twist */
	uint8_t payload[XR_PACKET_PAYLOAD_LEN];
} xr_grid_entity_packet_t;

static inline void xr__pu32(uint8_t *b, uint32_t v) {
	b[0] = (uint8_t)(v);       b[1] = (uint8_t)(v >> 8);
	b[2] = (uint8_t)(v >> 16); b[3] = (uint8_t)(v >> 24);
}
static inline uint32_t xr__gu32(const uint8_t *b) {
	return (uint32_t)b[0] | ((uint32_t)b[1] << 8) | ((uint32_t)b[2] << 16) | ((uint32_t)b[3] << 24);
}
static inline void xr__pi64(uint8_t *b, int64_t v) {
	uint64_t u = (uint64_t)v;
	for (int i = 0; i < 8; i++) b[i] = (uint8_t)(u >> (i * 8));
}
static inline int64_t xr__gi64(const uint8_t *b) {
	uint64_t u = 0;
	for (int i = 0; i < 8; i++) u |= (uint64_t)b[i] << (i * 8);
	return (int64_t)u;
}
static inline void xr__pi16(uint8_t *b, int16_t v) {
	uint16_t u = (uint16_t)v;
	b[0] = (uint8_t)(u); b[1] = (uint8_t)(u >> 8);
}
static inline int16_t xr__gi16(const uint8_t *b) {
	return (int16_t)((uint16_t)b[0] | ((uint16_t)b[1] << 8));
}

/* `out` must have room for XR_PACKET_SIZE bytes. Every byte is written, including the
 * unassigned gap at 36..39, so an encode never leaks whatever was in the caller's buffer. */
static inline void xr_grid_entity_packet_encode(const xr_grid_entity_packet_t *p, uint8_t *out) {
	for (int i = 0; i < XR_PACKET_SIZE; i++) out[i] = 0;
	xr__pu32(out + XR_PACKET_OFF_GID, p->gid);
	xr__pi64(out + XR_PACKET_OFF_POS + 0, p->pos_um_x);
	xr__pi64(out + XR_PACKET_OFF_POS + 8, p->pos_um_y);
	xr__pi64(out + XR_PACKET_OFF_POS + 16, p->pos_um_z);
	xr__pi16(out + XR_PACKET_OFF_VEL + 0, p->vel_x);
	xr__pi16(out + XR_PACKET_OFF_VEL + 2, p->vel_y);
	xr__pi16(out + XR_PACKET_OFF_VEL + 4, p->vel_z);
	xr__pu32(out + XR_PACKET_OFF_HLC, p->hlc);
	xr__pu32(out + XR_PACKET_OFF_CLASS_OWNER, p->class_owner);
	xr__pu32(out + XR_PACKET_OFF_SUB_INDEX, p->sub_index);
	xr__pi16(out + XR_PACKET_OFF_ROT + 0, p->rot_x);
	xr__pi16(out + XR_PACKET_OFF_ROT + 2, p->rot_y);
	xr__pi16(out + XR_PACKET_OFF_ROT + 4, p->rot_z);
	for (int i = 0; i < XR_PACKET_PAYLOAD_LEN; i++)
		out[XR_PACKET_PAYLOAD_OFFSET + i] = p->payload[i];
}

static inline void xr_grid_entity_packet_decode(const uint8_t *in, xr_grid_entity_packet_t *p) {
	p->gid = xr__gu32(in + XR_PACKET_OFF_GID);
	p->pos_um_x = xr__gi64(in + XR_PACKET_OFF_POS + 0);
	p->pos_um_y = xr__gi64(in + XR_PACKET_OFF_POS + 8);
	p->pos_um_z = xr__gi64(in + XR_PACKET_OFF_POS + 16);
	p->vel_x = xr__gi16(in + XR_PACKET_OFF_VEL + 0);
	p->vel_y = xr__gi16(in + XR_PACKET_OFF_VEL + 2);
	p->vel_z = xr__gi16(in + XR_PACKET_OFF_VEL + 4);
	p->hlc = xr__gu32(in + XR_PACKET_OFF_HLC);
	p->class_owner = xr__gu32(in + XR_PACKET_OFF_CLASS_OWNER);
	p->sub_index = xr__gu32(in + XR_PACKET_OFF_SUB_INDEX);
	p->rot_x = xr__gi16(in + XR_PACKET_OFF_ROT + 0);
	p->rot_y = xr__gi16(in + XR_PACKET_OFF_ROT + 2);
	p->rot_z = xr__gi16(in + XR_PACKET_OFF_ROT + 4);
	for (int i = 0; i < XR_PACKET_PAYLOAD_LEN; i++)
		p->payload[i] = in[XR_PACKET_PAYLOAD_OFFSET + i];
}

#ifdef __cplusplus
}
#endif

#endif
